### ISSUE TITLE
Create Use Case Diagram

### ISSUE THREAD

**Issue by Khanrasheed472** [Valdarie/INF2001-P3-T4#1]
**Task Title ID:** #1

**What is the task about? Please describe in detail.**
To create a visual representation, in the form of a use case diagram, illustrating the interactions between users and the system, as well as the system's behaviour.

**What are the goals of this task? Please describe in detail.**
To capture and represent the system's functionalities, interactions, and boundaries to provide a clear understanding of the system's requirements.

**Success or completion criteria. Please describe in detail.**
The use case diagram should depict all relevant actors, use cases, and system boundaries accurately, aligning with the project requirements.

**Allocated Time:** 8 hours

**Start date and end date of the task.**
Start Date: 7 September 2023
End Date: 19 September 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Osama Rasheed Khan @Khanrasheed472 

**The status of the task. (Usually in the initial column "To-Do")**
In-Progress

**What is the priority of this task?**
High

**Comment by Xuanting85** [comment]
**Describe the work done in detail.**


**Has this work been committed to the repo?**


**How does the work affect "4. Success or completion criteria"?**


**Start date and end date of the work done.**

**Comment by Khanrasheed472** [comment]
Describe the work done in detail.
Created a Use-Case diagram using the draw.io platform to illustrate the interactions between the actors (Manager, Staff, and IT Admin) and the System. The use case diagram has been updated once after consulting with the professor on the initial design.

Has this work been committed to the repo?
no

How does the work affect "4. Success or completion criteria"?
Creates a visual representation of the system's functionality and its interactions with the actors, hence, giving a clear understanding of how the users interact with the system and its behaviour.

Start date and end date of the work done:

Start Date: 13 September 2023
End Date: 19 September 2023
