### ISSUE TITLE
Project Meeting 05: Final M1 Report Updates

### ISSUE THREAD

**Issue by Khanrasheed472** [Valdarie/INF2001-P3-T4#10]
**Task Title ID:** #10

**What is the task about? Please describe in detail.**
To finish up the report and make changes to existing contents in the report, based on given feedback, before submission.

**What are the goals of this task? Please describe in detail.**
Ensure that the contents in all the sections are accurate and updated, and are properly cited,

**Success or completion criteria. Please describe in detail.**
- The M1 report is updated with all relevant information.
- The language and formatting are consistent and professional.
- The report accurately represents the progress and achievements of Milestone 1.

**Allocated Time:** 5 hours

**Start date and end date of the task.**
Start Date: 21 September 2023
End Date: 21 September 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Ashlinder

**The status of the task. (Usually in the initial column "To-Do")**
To-Do (High Priority)

**What is the priority of this task?**
High

**Comment by Xuanting85** [comment]
**Reason for delay**
We had another meeting to complete the report and update the Gantt chart, on Friday 22nd Sep. Hence, we will be merging two meetings into one issue.

**Comment by Xuanting85** [comment]
**Describe the work done in detail.**
Reviewed the current M1 report, identified areas for improvement, updated content, refined language, and incorporated any final details to enhance the overall quality of the report.

**Has this work been committed to the repo?**
No.

**How does the work affect "4. Success or completion criteria"?**
The updates and improvements made ensure that the report meets the defined success criteria, presenting an accurate reflection of M1.

**Start date and end date of the work done.**
Start Date: 21 September 2023
End Date: 22 September 2023
