### ISSUE TITLE
Follow-up Email to Client

### ISSUE THREAD

**Issue by Valdarie** [Valdarie/INF2001-P3-T4#11]
**Task Title ID:** #11

**What is the task about? Please describe in detail.**
Post interview follow-up email to client to confirm details discussed and check on additional requirements.

**What are the goals of this task? Please describe in detail.**
Write an email to the client to confirm the system requirement details discussed. 

**Success or completion criteria. Please describe in detail.**
Email to be written and sent out.

**Allocated Time:**
15 minutes

**Start date and end date of the task.**
Start Date: 13 September 2023
End Date: 19 September 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Osama Rasheed Khan

**The status of the task. (Usually in the initial column "To-Do")**
In-Progress

**What is the priority of this task?**
High

**Comment by Xuanting85** [comment]
**Describe the work done in detail.**


**Has this work been committed to the repo?**


**How does the work affect "4. Success or completion criteria"?**


**Start date and end date of the work done.**

**Comment by Khanrasheed472** [comment]
Describe the work done in detail.
Write follow-up email to professor to confirm details discussed during first interview

Has this work been committed to the repo?
no

How does the work affect "4. Success or completion criteria"?
We clarified our doubts and were better able to understand the user requirements.

Start date and end date of the work done.
13 September 2023
19 September 2023
