### ISSUE TITLE
Create Boundary Classes

### ISSUE THREAD

**Issue by Xuanting85** [Valdarie/INF2001-P3-T4#15]
**Task Title ID:** #15

**What is the task about? Please describe in detail.**
This task involves the creation of boundary classes responsible for handling the interaction between the system and external entities, such as user interfaces, file systems, or network connections. Boundary classes act as interfaces for data input and output.

**What are the goals of this task? Please describe in detail.**
- Develop boundary classes that manage the exchange of data between the system and external entities.
- Implement methods within the boundary classes to handle input from external sources and display relevant information to users.

**Success or completion criteria. Please describe in detail.**
Boundary classes are successfully implemented and seamlessly integrated into the system.
Input from external sources is appropriately processed by the boundary classes.
Output displayed to users through the boundary classes is clear and conforms to the system's requirements.

**Allocated Time:** 2 hours

**Start date and end date of the task.**
Start Date: 8 October 2023
End Date: 11 October 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Ashlinder @Ashlinder 

**The status of the task. (Usually in the initial column "To-Do")**
Closed

**What is the priority of this task?**
High Priority

**Comment by Khanrasheed472** [comment]
Describe the work done in detail:
Develop boundary classes that manage the exchange of data between the system and external entities.
Implement methods within the boundary classes to handle input from external sources and display relevant information to users.

Has this work been committed to the repo?
no

How does the work affect "4. Success or completion criteria"?
Boundary classes are successfully implemented and seamlessly integrated into the system.
Input from external sources is appropriately processed by the boundary classes.
Output displayed to users through the boundary classes is clear and conforms to the system's requirements.

Start date and end date of the work done.
Start Date: 8 October 2023
End Date: 11 October 2023
