### ISSUE TITLE
Create Interface Classes

### ISSUE THREAD

**Issue by Xuanting85** [Valdarie/INF2001-P3-T4#16]
**Task Title ID:** #16

**What is the task about? Please describe in detail.**
This task involves designing and implementing interface classes that define the contracts for communication between different components within the system. Interface classes help establish a clear and standardized way for components to interact.

**What are the goals of this task? Please describe in detail.**
- Define interface classes that specify the methods and properties required for communication.
- Ensure that the interface classes facilitate loose coupling between components, promoting flexibility and modularity.

**Success or completion criteria. Please describe in detail.**
- Interface classes are successfully implemented, adhering to the defined contracts.
- Components interacting through the interfaces achieve the desired functionality without tight dependencies.
- The use of interface classes enhances the maintainability and extensibility of the system.

**Allocated Time:** 3 hours

**Start date and end date of the task.**
Start Date: 12 October 2023
End Date: 16 October 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Seri @suhree777 

**The status of the task. (Usually in the initial column "To-Do")**
Completed

**What is the priority of this task?**
High-Priority

**Comment by Khanrasheed472** [comment]
Describe the work done in detail:
Define interface classes that specify the methods and properties required for communication.
Ensure that the interface classes facilitate loose coupling between components, promoting flexibility and modularity.

Has this work been committed to the repo?
no

How does the work affect "4. Success or completion criteria"?
Interface classes are successfully implemented, adhering to the defined contracts.
Components interacting through the interfaces achieve the desired functionality without tight dependencies.
The use of interface classes enhances the maintainability and extensibility of the system.

Start date and end date of the work done.
Start Date: 12 October 2023
End Date: 16 October 2023
