### ISSUE TITLE
Project Meeting 02: Client Meeting

### ISSUE THREAD

**Issue by Valdarie** [Valdarie/INF2001-P3-T4#18]
**Task Title ID:** #18

**What is the task about? Please describe in detail.**
To have a meeting with the client to gain a clear understanding of his/her initial requirements for the project, discuss his/her expectations, and any other features wished to be included in the system.

**What are the goals of this task? Please describe in detail.**
- To gather comprehensive information about the client's requirements, clarify any ambiguities or uncertainties, and ensure that the client's expectations are aligned with the team's understanding.
- To establish a solid foundation for project planning and management.

**Success or completion criteria. Please describe in detail.**
When all initial requirements have been accurately documented, and questions or uncertainties have been clarified.

**Allocated Time:** 15 mins

**Start date and end date of the task.**
Start Date: 5 September 2023
End Date: 5 September 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Teo Xuanting

**The status of the task. (Usually in the initial column "To-Do")**
Completed

**What is the priority of this task?**
High

**Comment by Xuanting85** [comment]
**Describe the work done in detail.**
We met with the client to discuss and clarify his initial requirements for the system, asked questions with regard to the company in the project description, and took down notes for requirements that we were unclear about.

**Has this work been committed to the repo?**
No.

**How does the work affect "4. Success or completion criteria"?**
It significantly impacts "4. Success or completion criteria" as this meeting forms the basic understanding of the client's initial requirements. A clear understanding of the client's expectations and requirements is vital for meeting the success criteria and ensuring that the subsequent project phases are aligned with the needs.

**Start date and end date of the work done.**
Start Date: 5 September 2023
End Date: 5 September 2023
