### ISSUE TITLE
Functional User Requirement Documentation

### ISSUE THREAD

**Issue by Khanrasheed472** [Valdarie/INF2001-P3-T4#2]
**Task Title ID:** #2

**What is the task about? Please describe in detail.**
Documenting the functional user requirements for the project. It includes detailing the specific functionalities and features the system must provide to meet user needs and expectations.

**What are the goals of this task? Please describe in detail.**
To compile a comprehensive and clear documentation of the functional user requirements, for subsequent product design and implementation.

**Success or completion criteria. Please describe in detail.**
A detailed and exhaustive document outlining each functional user requirement, complete with descriptions

**Allocated Time:** 3 hours

**Start date and end date of the task.**
Start Date: 13 September 2023
End Date: 13 September 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Teo Xuanting @Xuanting85 

**The status of the task. (Usually in the initial column "To-Do")**
Completed

**What is the priority of this task?**
High

**Comment by Xuanting85** [comment]
**Describe the work done in detail.**
Documenting the functional user requirements for the project. It includes detailing the specific functionalities and features the system must provide to meet user needs and expectations.

**Has this work been committed to the repo?**
No

**How does the work affect "4. Success or completion criteria"?**
It has contributed by providing a well-detailed and comprehensive functional user requirements document, which is essential for guiding the development process effectively and ensuring alignment with client's needs.

**Start date and end date of the work done.**
Start Date: 13 September 2023
End Date: 13 September 2023
