### ISSUE TITLE
Update Website Figma

### ISSUE THREAD

**Issue by Xuanting85** [Valdarie/INF2001-P3-T4#25]
**Task Title ID:** #25

**What is the task about? Please describe in detail.**
The task involves creating the official prototype for the Ferry Workload Management System using Figma. Figma is a collaborative design tool that allows for the creation of interactive and visually appealing prototypes.

**What are the goals of this task? Please describe in detail.**
User-Centric Design: Ensure that the prototype is designed with a focus on user experience, making it intuitive and easy to navigate for IT Admins, Managers, and Staff members.

Functional Representation: Clearly represent the functionalities outlined in the system requirements, incorporating wireframes and design elements that align with the use cases and scenarios.

Consistency and Branding: Maintain a consistent design language and branding throughout the prototype, ensuring a cohesive and professional look and feel.

Interactive Elements: Implement interactive elements within the prototype to simulate the user flow and functionality, allowing stakeholders to visualize how the system will work.

Accessibility: Consider accessibility standards and ensure that the prototype is usable by individuals with diverse needs, including those with disabilities.

**Success or completion criteria. Please describe in detail.**
Completion of Key Screens: All key screens, including login pages, user dashboards, and task-specific pages, should be designed and visually represented.

Functional Interactivity: Interactive elements, such as buttons, dropdowns, and navigation, should be implemented to demonstrate the flow and functionality of the system.

Consistent Design Language: The design should adhere to a consistent color scheme, typography, and layout, reflecting the established branding guidelines.

Accessibility Features: Ensure that the prototype incorporates accessibility features, such as alternative text for images and proper contrast ratios for text readability.

Alignment with Use Cases: Verify that the prototype aligns with the specified use cases and scenarios outlined in the system requirements.

**Allocated Time:** 
11 Days

**Start date and end date of the task.**
Start Date: 10 Novemeber 2023
End Date: 21 November 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
@suhree777 
**The status of the task. (Usually in the initial column "To-Do")**
Completed

**What is the priority of this task?**
High

**Comment by suhree777** [comment]
**Describe the work done in detail.**
The work involved the comprehensive design of the official prototype for the Ferry Workload Management System using Figma. It included the creation of key screens such as login pages, user dashboards, and task-specific pages, ensuring that each screen accurately represented the functionalities outlined in the system requirements. The design process focused on user-centric principles, incorporating interactive elements to simulate the system's functionality. Consistent branding and design language were maintained throughout, and accessibility features were implemented to ensure usability for a diverse user base.

**Has this work been committed to the repo?**
No

**How does the work affect "4. Success or completion criteria"?**
The completion of the task aligns with the success criteria outlined for the prototype design. All key screens have been designed, interactive elements have been implemented to demonstrate functionality, a consistent design language has been maintained and  accessibility features are in place.

**Start date and end date of the work done.**
Start Date: 10 November 2023
End Date: 21 September 2023
