### ISSUE TITLE
Related Background Literature (section 1.2) in M1 Report

### ISSUE THREAD

**Issue by Xuanting85** [Valdarie/INF2001-P3-T4#29]
**Task Title ID:** #29

**What is the task about? Please describe in detail.**
Task involves creating a comprehensive background literature review of a Ferry WOrkload Manaegment System. The literature review aims to provide an indepth understanding of the existing knowledge and practices related to ferry workload management system. 

**What are the goals of this task? Please describe in detail.**
Goal is to get a deep and comprehensive knowledge of the field of ferry workload management systems which includes understanding the challenges faced and existing solutions, and to also identify best practices and lessons learned from exisitng literature reviews that can be applied to the development of ferry workload management system.

**Success or completion criteria. Please describe in detail.**
To have the literature review be solely focused on ferry workload management systems and to provide a clear indentification of challenges and issuses related to ferry workload management system.

**Allocated Time:** 5 days

**Start date and end date of the task.**
Start Date: 15 Sept 2023
End Date: 20 Sept 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Seri Hanzalah Bte Haniffah

**The status of the task. (Usually in the initial column "To-Do")**
Completed

**What is the priority of this task?**
High

**Comment by suhree777** [comment]
**Describe the work done in detail.**
Conducted extensive research and create a comprehensive literature review for Ferry Workload Management system. THis involves identifying key concepts , conducting a thorough literature review and organising the information into a coherent narrative. Aim was to provide a foundational understanding of ferry workload management stystem and gather insights to inform the systems development.

**Has this work been committed to the repo?**
No.

**How does the work affect "4. Success or completion criteria"?**
It ensures the knowledge base of ferry workload management system, the problem statement, best practices are documented in a clear and precise manner.

**Start date and end date of the work done.**
Start Date: 15 September 2023
End Date: 20 September 2023
