### ISSUE TITLE
Non Functional User Requirement Documentation

### ISSUE THREAD

**Issue by Khanrasheed472** [Valdarie/INF2001-P3-T4#3]
**Task Title ID:  #3**

**What is the task about? Please describe in detail.**
To document the non functional user requirements for the project. This involves detailing specififc non-functional asepects and constraints the the system must follow in order to meet user needs and expectations.

**What are the goals of this task? Please describe in detail.**
To compile a comprehensive and clear documentation of the non functional user requirements. The doucmentation serve as a crucial reference for the subsequent phases of product design implementation.

**Success or completion criteria. Please describe in detail.**
A detailed and exhaustive document is created, outlining each non functional user requirement with clear descriptions of the constraints and expectations.

**Allocated Time:** 3 hours

**Start date and end date of the task.**
**Start Date:** 13 September 2023
**End Date:**  13 September 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Seri Hanzalah Bte Haniffah

**The status of the task. (Usually in the initial column "To-Do")**
Completed

**What is the priority of this task?**
High

**Comment by suhree777** [comment]
**Describe the work done in detail.**
Documenting the non functional user requirements for the project. This includes capturing the specififc non functional aspects, constraints and qualities that the system must have to fulfill user expectations effectively.

**Has this work been committed to the repo?**
No

**How does the work affect "4. Success or completion criteria"?**
It has contributed by providing a well-detailed and comprehensive non functional user requirements document, which is essential for guiding the development process effectively and ensuring alignment with client's needs.

**Start date and end date of the work done.**
Start Date: 13 September 2023
End Date: 13 September 2023
