### ISSUE TITLE
Create Entity Classes

### ISSUE THREAD

**Issue by Khanrasheed472** [Valdarie/INF2001-P3-T4#38]
**Task Title ID:** https://github.com/Valdarie/INF2001-P3-T4/issues/38

**What is the task about? Please describe in detail.**
This task involves creating a new entity class as part of the project development. The entity class should encapsulate relevant attributes and behaviours to represent a specific concept within the project scope.

**What are the goals of this task? Please describe in detail.**
- Define and implement the necessary attributes and methods for the new entity class.
- Ensure that the entity class adheres to the project's design and coding standards.

**Success or completion criteria. Please describe in detail.**
- All attributes in the entity classes are properly defined with their data types and access modifiers.
- Each entity class is to have their methods that represent its behaviours.

**Allocated Time:** 3 hours

**Start date and end date of the task.**
Start Date: 1 October 2023
End Date: 4 October 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Teo Xuanting @Xuanting85 

**The status of the task. (Usually in the initial column "To-Do")**
In-Progress

**What is the priority of this task?**
High

**Comment by Xuanting85** [comment]
**Reason for delay:**
Modifying the diagram based on prof's feedback

**Comment by Xuanting85** [comment]
**Describe the work done in detail.**
Initiated the creation of the new entity classes, which involved defining and implementing the essential attributes and methods within the classes.

**Has this work been committed to the repo?**
No

**How does the work affect "4. Success or completion criteria"?**
It contributed to the completion criteria as it laid the foundation for the entity class. However, full compliance with the criteria will be assessed upon the class's completion and integration into the project.

**Start date and end date of the work done:**
Start Date: 1 October 2023
End Date: 25 October 2023
