### ISSUE TITLE
Create Gantt Chart

### ISSUE THREAD

**Issue by Khanrasheed472** [Valdarie/INF2001-P3-T4#4]
**Task Title ID:** #4

**What is the task about? Please describe in detail.**
To provide a visual representation of the project schedule that outlines the tasks, durations, assignees, and dependencies (if any)

**What are the goals of this task? Please describe in detail.**
To plan and organise the project tasks, allocate enough time for each task, 

**Success or completion criteria. Please describe in detail.**
- Planned tasks for the project have been added to the chart.
- All tasks have resource(s) allocated.
- Tasks are in line with the project's goals, and vision.
- Chart to accurately reflect current project status and progress.

**Allocated Time:** 3 days

**Start date and end date of the task.**
Start Date: 19 September 2023
End Date: 21 September 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Teo Xuanting

**The status of the task. (Usually in the initial column "To-Do")**
In-Progress

**What is the priority of this task?**
High

**Comment by Xuanting85** [comment]
**Task Title ID:** #4

**What is the task about? Please describe in detail.**
To provide a visual representation of the project schedule that outlines the tasks, durations, assignees, and dependencies (if any)

**What are the goals of this task? Please describe in detail.**
To plan and organise the project tasks, allocate enough time for each task, 

**Success or completion criteria. Please describe in detail.**
- Planned tasks for the project have been added to the chart.
- All tasks have resource(s) allocated.
- Tasks are in line with the project's goals, vision.
- Chart to accurately reflect current project status and progress.

**Allocated Time:**

**Start date and end date of the task.**
Start Date: 7 September 2023
End Date: November 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Teo Xuanting

**The status of the task. (Usually in the initial column "To-Do")**
In-Progress

**What is the priority of this task?**
High

**Comment by Xuanting85** [comment]
**Describe the work done in detail.**
- Created a visual representation of the project schedule with tasks, durations and assignees.
- Included tasks for M1, and have identified potential tasks for M2 and M3.

**Has this work been committed to the repo?**
No.

**How does the work affect "4. Success or completion criteria"?**
- The Gantt chart now includes planned tasks for the project, ensuring alignment with project goals and vision.
- Resource allocation for each task aids in better management and tracking of progress.
- The Gantt chart accurately reflects the current project status, supporting effective project management.

**Start date and end date of the work done.**
Start Date: 19 September 2023
End Date: 21 September 2023
