### ISSUE TITLE
Project Meeting 01: Prepare Requirements Questionnaire for Clients

### ISSUE THREAD

**Issue by Valdarie** [Valdarie/INF2001-P3-T4#5]
**Task Title ID:** #5

**What is the task about? Please describe in detail.**
Creating a comprehensive set of structured questions and inquiries to understand the client's needs, expectations, and specifications for the workload management system as described in the project description.

**What are the goals of this task? Please describe in detail.**
The goal is to construct a questionnaire that successfully elicits key information from the client, thus facilitating a clear knowledge of their needs and enabling the development of a customised system that addresses them.

**Success or completion criteria. Please describe in detail.**
A well-structured questionnaire that asks specific, relevant questions on every aspect of the system.

**Allocated Time:** 3 hours

**Start date and end date of the task.** 
Start Date: 30 August 2023
End Date: 30 August 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
All members

**The status of the task. (Usually in the initial column "To-Do")**
Completed

**What is the priority of this task?**
High

**Comment by Xuanting85** [comment]
**Describe the work done in detail.**
review the project description, extracting crucial information, requirements, and potential areas needing clarification. We brainstormed and formulated a set of structured questions and inquiries aimed at comprehensively understanding the client's needs, expectations, and specific requirements for the workload management system. 

**Has this work been committed to the repo?**
No.

**How does the work affect "4. Success or completion criteria"?**
This task significantly contributes to meeting the success or completion criteria. The creation of a well-structured questionnaire is fundamental for gaining a precise understanding of the client's requirements. The formulated questions are tailored to elicit specific, relevant information necessary to meet the project's objectives. Therefore, this task directly aligns with the completion criteria of producing a comprehensive set of questions.

**Start date and end date of the work done.**
Start Date: 30 August 2023
End Date: 30 August 2023
