### ISSUE TITLE
Set Up GitHub Wiki Page

### ISSUE THREAD

**Issue by Valdarie** [Valdarie/INF2001-P3-T4#6]
**Task Title ID:** #6

**What is the task about? Please describe in detail.**
Setting up the wiki page to provide an introduction to the group's project, outline the approach in addressing the project's problem, and document any project updates along the way.

**What are the goals of this task? Please describe in detail.**
To create a centralised and easily accessible platform (GitHub Wiki page) to document our project, which includes project introduction, defining of the identified problem, presenting our approaches and solutions, and project updates.

**Success or completion criteria. Please describe in detail.**
1. GitHub Wiki page is created and structured.
2. Project's Introduction is well-detailed.
3. Problem statement is clearly defined.
4. Approach and strategies to address the problem are outlined.
5. Wiki is easily accessible to the team members.

**Allocated Time:** 2 hours

**Start date and end date of the task.**
Start Date: 30 August 2023
End Date: 30 Agust 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Leo En Qi Valerie, Osama Rasheed Khan

**The status of the task. (Usually in the initial column "To-Do")**
Completed

**What is the priority of this task?**
Low

**Comment by Xuanting85** [comment]
**Describe the work done in detail.**
We have composed an overview detailing the project's scope, identified the challenges within the current system, outlined our objectives to overcome these challenges, and presented our envisioned functioning of the system.

**Has this work been committed to the repo?**
No.

**How does the work affect "4. Success or completion criteria"?**
We have established a strong foundation for our project documentation. The structured introduction sets the tone for the subsequent sections, ensuring that our project's goals, challenges, and vision are clearly articulated and aligned with the intended outcomes.

**Start date and end date of the work done.**
Start Date: 30 August 2023
End Date: 30 Agust 2023
