### ISSUE TITLE
Report Introduction (section 1.1 and 1.3) in M1 Report

### ISSUE THREAD

**Issue by Khanrasheed472** [Valdarie/INF2001-P3-T4#7]
**Task Title ID:** #7

**What is the task about? Please describe in detail.**
This task is to provide a brief introduction and the intended purpose of our project.
Additionally, it includes a description of the product scope and relevant background research information related to our project. 

**What are the goals of this task? Please describe in detail.**
The goal of this task is to provide readers with a comprehensive overview of our project as well as an outline of our report. Readers will have a better understanding of our project and be able to navigate through the different sections of the report that are crucial for them. 

**Success or completion criteria. Please describe in detail.**
The completion criteria for this task would be to write up the following sections of the report:
1 Introduction
1.1 Product Scope
1.3 Intended Audience and Document Overview

**Allocated Time:** 3 days

**Start date and end date of the task.**

Start Date: 12 Sep 2023
End Date: 14 Sep 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Ashlinder

**The status of the task. (Usually in the initial column "To-Do")**
Completed

**What is the priority of this task?**
Medium

**Comment by Xuanting85** [comment]
**Describe the work done in detail.**
- Researching and gathering relevant information for the project introduction.
- Defining the product scope to ensure a clear understanding of the project's boundaries.
- Taking into account the intended audience and crafting an overview of the document to align with their requirements.

**Has this work been committed to the repo?**
No.

**How does the work affect "4. Success or completion criteria"?**
lays the foundation for the project overview and ensures that the specified sections in the completion criteria are documented comprehensively and in alignment with the project's objectives.

**Start date and end date of the work done.**
Start Date: 12 Sep 2023
End Date: 14 Sep 2023
